name             'chef-base'
maintainer       'Philip Hutchins'
maintainer_email 'flipture@gmail.com'
license          'MIT'
description      'Base node management cookbook'
long_description 'Base node management cookbook'
version          '0.2.2'

depends 'chef-iptables', '~> 0.1.1'
depends 'chef-client', '~> 7.0.0'
depends 'sar', '~> 0.0.1'
