default['chef_client']['init_style'] = 'upstart'
default['chef_client']['interval'] = '1800'
default['chef_client']['splay'] = '600'
default['chef_client']['log_file'] = 'client.log'
default['chef_client']['log_dir'] = '/var/log/chef'
